version: '3.9'

services:
  back_base:
    restart: no
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - mi_red
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/prueba
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: clave

  mysql:
    restart: always
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - db-data-test:/var/lib/mysql_data
    environment:
      MYSQL_ROOT_PASSWORD: clave
    networks:
      - mi_red

networks:
  mi_red:

volumes:
  db-data-test: